namespace SportsData.Api.Application.Previews.Models;

public class MatchupPreviewResponse
{
    public required string Overview { get; set; }

    public required string Analysis { get; set; }

    public required string Prediction { get; set; }

    public Guid PredictedStraightUpWinner { get; set; }

    public Guid? PredictedSpreadWinner { get; set; }

    public int? OverUnderPrediction { get; set; }

    public int AwayScore { get; set; }

    public int HomeScore { get; set; }
}

public class MatchupPreviewResponseV2
{
    public required string Overview { get; set; }

    public required string Analysis { get; set; }

    public PredictionPayload Prediction { get; set; } = null!;

    public class PredictionPayload
    {
        public Guid PredictedStraightUpWinner { get; set; }

        public Guid? PredictedSpreadWinner { get; set; }

        public int OverUnderPrediction { get; set; }

        public int AwayScore { get; set; }

        public int HomeScore { get; set; }
    }
}

public static class MatchupPreviewResponseExtensions
{
    public static MatchupPreviewResponse ToV1(this MatchupPreviewResponseV2 v2)
    {
        if (v2 is null) throw new ArgumentNullException(nameof(v2));
        if (v2.Prediction is null) throw new ArgumentException("Prediction section cannot be null", nameof(v2));

        return new MatchupPreviewResponse
        {
            Overview = v2.Overview,
            Analysis = v2.Analysis,
            Prediction = "Generated by model",
            PredictedStraightUpWinner = v2.Prediction.PredictedStraightUpWinner,
            PredictedSpreadWinner = v2.Prediction.PredictedSpreadWinner,
            OverUnderPrediction = v2.Prediction.OverUnderPrediction,
            AwayScore = v2.Prediction.AwayScore,
            HomeScore = v2.Prediction.HomeScore
        };
    }
}

