trigger:
- main

pool:
  vmImage: 'windows-latest'

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '31f2836a-84b3-4ad0-bf15-f4ea41754d06'
  imageRepository: 'sportsdatacontest'
  containerRegistry: 'sportdeets.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/src/SportsData.Contest/Dockerfile'
  tag: '$(Build.BuildId)'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

  # Build Solution Vars
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  Major: '1'
  Minor: '0'
  Patch: '1'
  PackageVersion: '1.0.1'

  # Deploy Vars
  azureSubscription: 'dev-sports-data-connection'
  appName: 'dev-sdcontest'

stages:
- stage: BuildAndTest
  jobs:
  - job: BuildAndTest
    displayName: BuildAndTest
    steps:
    - task: UseDotNet@2
      displayName: 'Use .NET 9 SDK'
      inputs:
        packageType: 'sdk'
        version: '9.0.x'
        includePreviewVersions: true

    - task: NuGetCommand@2
      displayName: 'NuGet Restore'
      inputs:
        command: 'restore'
        restoreSolution: '**/sports-data-contest.sln'
        feedsToUse: 'select'
        vstsFeed: '2bb0cd0d-fa6e-42f0-9b7e-9cc1ce065e55/de94ed5a-8390-4547-bdd9-f975a712aa70'
    
    - task: MSBuild@1
      displayName: 'Build sports-data-contest solution'
      inputs:
        solution: '**\sports-data-api.sln'
        msbuildArchitecture: 'x64'
        clean: true
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'
        restoreNugetPackages: true
        msbuildArguments: '/t:Restore'

    - task: DotNetCoreCLI@2
      displayName: 'Run Unit Tests'
      inputs:
        command: 'test'
        projects: '**/SportsData.Contest.Tests.Unit.csproj'
        testRunTitle: 'contest-tests-unit'

    - task: DotNetCoreCLI@2
      displayName: 'Run Integration Tests'
      inputs:
        command: 'test'
        projects: '**/SportsData.Contest.Tests.Integration.csproj'
        testRunTitle: 'contest-tests-int'