using FluentAssertions;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Routing;

using SportsData.Api.Application.Admin;

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Runtime.CompilerServices;

using Xunit;

namespace SportsData.Api.Tests.Unit.Routing;

/// <summary>
/// Pins the API's entire public surface — every verb, every route template, and
/// the effective authorization on each — to a committed snapshot.
/// </summary>
/// <remarks>
/// Written for the AdminController break-up (docs/refactor/admin-controller-vsa-split.md),
/// where ~59 endpoints move between files and change route. Two jobs:
/// <para>
/// 1. <b>It is the review artifact.</b> A refactor PR that moves endpoints shows
/// up here as a readable diff — this route out, that route in — instead of
/// forcing a reviewer to infer the wire contract from a pile of moved files.
/// </para>
/// <para>
/// 2. <b>It is the authorization ledger.</b> Once <c>admin/</c> is gone from the
/// URI, nothing in a path says "this one is privileged". A dropped
/// <c>[AdminApiToken]</c> during a move would otherwise produce no compile
/// error and no failing test — just a silently public admin endpoint. Here it
/// is a one-line diff on a line a human is already reading.
/// </para>
/// <para>
/// Reflection over the controllers rather than a booted host on purpose: this
/// has to run in the unit suite (the PR gate) with no configuration, database,
/// or network. Every controller in this service routes by explicit attributes,
/// so what is read here is what ASP.NET will register.
/// </para>
/// </remarks>
public class RouteTableSnapshotTests
{
    [Fact]
    public void RouteTable_MatchesSnapshot()
    {
        var actual = BuildInventory();
        var path = SnapshotPath();

        if (!File.Exists(path))
        {
            File.WriteAllLines(path, actual);
            Assert.Fail(
                $"No route snapshot existed, so one was written to {path}. " +
                "Review it and commit it — it is the baseline every later refactor diffs against.");
        }

        var expected = File.ReadAllLines(path)
            .Where(l => !string.IsNullOrWhiteSpace(l) && !l.StartsWith('#'))
            .ToList();

        if (!expected.SequenceEqual(actual))
        {
            var added = actual.Except(expected).ToList();
            var removed = expected.Except(actual).ToList();

            Assert.Fail(
                "The API route table no longer matches the committed snapshot.\n\n" +
                "If this PR deliberately moves or renames routes, that is expected — " +
                $"regenerate with:\n    ROUTE_SNAPSHOT_UPDATE=1 dotnet test --filter {nameof(RouteTable_MatchesSnapshot)}\n" +
                "then READ the diff before committing. Pay particular attention to any line " +
                "whose auth marker changed: losing [AdminApiToken] makes an admin endpoint public.\n\n" +
                $"Added ({added.Count}):\n  " + string.Join("\n  ", added) + "\n\n" +
                $"Removed ({removed.Count}):\n  " + string.Join("\n  ", removed));
        }
    }

    /// <summary>
    /// Two endpoints answering the same verb + template is a routing ambiguity:
    /// one silently shadows the other, or ASP.NET throws at startup. Easy to
    /// introduce while re-parenting routes, and invisible in a unit suite that
    /// never boots the host.
    /// </summary>
    [Fact]
    public void NoTwoEndpointsShareAVerbAndTemplate()
    {
        var duplicates = Endpoints()
            .GroupBy(e => $"{e.Verb} {e.Template}", StringComparer.OrdinalIgnoreCase)
            .Where(g => g.Count() > 1)
            .Select(g => $"{g.Key} <- {string.Join(", ", g.Select(x => $"{x.Controller}.{x.Action}"))}")
            .ToList();

        duplicates.Should().BeEmpty(
            "each verb+template pair must resolve to exactly one action");
    }

    // ── Inventory ────────────────────────────────────────────────────────────

    private sealed record Endpoint(string Verb, string Template, string Auth, string Controller, string Action);

    private static List<string> BuildInventory()
    {
        var lines = Endpoints()
            .Select(e => $"{e.Verb,-6} /{e.Template,-62} {e.Auth}".TrimEnd())
            .OrderBy(l => l, StringComparer.Ordinal)
            .ToList();

        if (Environment.GetEnvironmentVariable("ROUTE_SNAPSHOT_UPDATE") == "1")
        {
            File.WriteAllLines(SnapshotPath(), Header().Concat(lines));
        }

        return lines;
    }

    private static IEnumerable<string> Header() =>
    [
        "# API route table — generated by RouteTableSnapshotTests.",
        "# Regenerate: ROUTE_SNAPSHOT_UPDATE=1 dotnet test --filter RouteTable_MatchesSnapshot",
        "# The auth column is the EFFECTIVE authorization (controller attributes OR action attributes).",
        "# A line losing [AdminApiToken] means an admin endpoint became reachable without one.",
        ""
    ];

    private static IEnumerable<Endpoint> Endpoints()
    {
        var assembly = typeof(AdminApiTokenAttribute).Assembly;

        var controllers = assembly.GetTypes()
            .Where(t => t is { IsAbstract: false, IsPublic: true }
                        && typeof(ControllerBase).IsAssignableFrom(t));

        foreach (var controller in controllers)
        {
            var prefix = RoutePrefixFor(controller);

            var actions = controller.GetMethods(BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly)
                .Where(m => !m.IsSpecialName);

            foreach (var action in actions)
            {
                var verbAttrs = action.GetCustomAttributes<HttpMethodAttribute>(inherit: true).ToList();
                if (verbAttrs.Count == 0)
                    continue;

                var auth = EffectiveAuth(controller, action);

                foreach (var verbAttr in verbAttrs)
                {
                    var template = verbAttr.Template
                                   ?? action.GetCustomAttribute<RouteAttribute>(inherit: true)?.Template;

                    foreach (var verb in verbAttr.HttpMethods)
                    {
                        yield return new Endpoint(
                            verb,
                            Combine(prefix, template, controller),
                            auth,
                            controller.Name,
                            action.Name);
                    }
                }
            }
        }
    }

    /// <summary>
    /// A [Route] declared on the controller replaces any inherited one; only when
    /// the controller declares none does the base class's template apply. That
    /// matters here because <c>ApiControllerBase</c> carries
    /// <c>[Route("api/[controller]")]</c>, which most controllers override and a
    /// few deliberately do not.
    /// </summary>
    private static string? RoutePrefixFor(Type controller)
    {
        var declared = controller.GetCustomAttributes<RouteAttribute>(inherit: false).FirstOrDefault();
        if (declared is not null)
            return declared.Template;

        return controller.GetCustomAttributes<RouteAttribute>(inherit: true).FirstOrDefault()?.Template;
    }

    private static string Combine(string? prefix, string? template, Type controller)
    {
        // "~/" on an action escapes the controller prefix entirely.
        if (template is not null && template.StartsWith("~/", StringComparison.Ordinal))
            return Tokens(template[2..], controller);

        var parts = new[] { prefix, template }
            .Where(p => !string.IsNullOrWhiteSpace(p))
            .Select(p => p!.Trim('/'));

        return Tokens(string.Join('/', parts), controller);
    }

    private static string Tokens(string template, Type controller) =>
        template.Replace(
            "[controller]",
            controller.Name.EndsWith("Controller", StringComparison.Ordinal)
                ? controller.Name[..^"Controller".Length]
                : controller.Name,
            StringComparison.Ordinal);

    /// <summary>
    /// Effective authorization: an action's own attributes win, otherwise the
    /// controller's apply. Rendered as a stable, greppable marker so a change is
    /// obvious in a diff.
    /// </summary>
    private static string EffectiveAuth(Type controller, MethodInfo action)
    {
        if (action.GetCustomAttribute<AllowAnonymousAttribute>(inherit: true) is not null)
            return "[AllowAnonymous]";

        var markers = new List<string>();

        if (action.GetCustomAttribute<AdminApiTokenAttribute>(inherit: true) is not null ||
            controller.GetCustomAttribute<AdminApiTokenAttribute>(inherit: true) is not null)
        {
            markers.Add("[AdminApiToken]");
        }

        var authorize = action.GetCustomAttribute<AuthorizeAttribute>(inherit: true)
                        ?? controller.GetCustomAttribute<AuthorizeAttribute>(inherit: true);

        if (authorize is not null)
        {
            var detail = new List<string>();
            if (!string.IsNullOrWhiteSpace(authorize.Roles)) detail.Add($"Roles={authorize.Roles}");
            if (!string.IsNullOrWhiteSpace(authorize.Policy)) detail.Add($"Policy={authorize.Policy}");
            markers.Add(detail.Count > 0 ? $"[Authorize({string.Join(',', detail)})]" : "[Authorize]");
        }

        return markers.Count > 0 ? string.Join(" ", markers) : "(none)";
    }

    /// <summary>
    /// Resolved at compile time so the snapshot lives beside this file in source,
    /// not in a build-output directory nobody diffs.
    /// </summary>
    private static string SnapshotPath([CallerFilePath] string here = "") =>
        Path.Combine(Path.GetDirectoryName(here)!, "RouteTable.snapshot.txt");
}
