global:
   scrape_interval: 15s

scrape_configs:
   - job_name: 'node-exporter'
     static_configs:
       - targets: ['node-exporter:9100']
   - job_name: 'otlp-collector'
     scrape_interval: 5s
     static_configs:
       - targets: ['otlp-collector:8889']
       - targets: ['otlp-collector:8888']