const { withAndroidManifest, AndroidConfig } = require('@expo/config-plugins');

/**
 * Points FCM's system-displayed notifications at the app's notification
 * icon + brand color.
 *
 * Why this exists: the backend sends FCM messages WITH a notification
 * payload (FirebasePushNotificationSender), so when the app is backgrounded
 * the FCM SDK displays them directly — bypassing expo-notifications. That
 * path reads its small icon from the
 * `com.google.firebase.messaging.default_notification_icon` manifest
 * meta-data, which the expo-notifications config plugin does NOT set (it
 * sets only its own `expo.modules.notifications.*` keys). Without it,
 * Android falls back to a blank white circle in the status bar / shade.
 *
 * The `notification_icon` drawable and `notification_icon_color` color
 * resource referenced here are generated by the expo-notifications plugin
 * from its `icon` / `color` options in app.json — this plugin must stay in
 * the plugins array AFTER expo-notifications.
 */
const withFirebaseNotificationDefaults = (config) => {
  return withAndroidManifest(config, (config) => {
    const app = AndroidConfig.Manifest.getMainApplicationOrThrow(config.modResults);

    AndroidConfig.Manifest.addMetaDataItemToMainApplication(
      app,
      'com.google.firebase.messaging.default_notification_icon',
      '@drawable/notification_icon',
      'resource',
    );
    AndroidConfig.Manifest.addMetaDataItemToMainApplication(
      app,
      'com.google.firebase.messaging.default_notification_color',
      '@color/notification_icon_color',
      'resource',
    );

    return config;
  });
};

module.exports = withFirebaseNotificationDefaults;
