const { withAndroidManifest, AndroidConfig } = require('@expo/config-plugins');

/**
 * Points FCM's system-displayed notifications at the app's notification
 * icon + brand color.
 *
 * Why this exists: the backend sends FCM messages WITH a notification
 * payload (FirebasePushNotificationSender), so when the app is backgrounded
 * the FCM SDK displays them directly — bypassing expo-notifications. That
 * path reads its small icon from the
 * `com.google.firebase.messaging.default_notification_icon` manifest
 * meta-data, which the expo-notifications config plugin does NOT set (it
 * sets only its own `expo.modules.notifications.*` keys). Without it,
 * Android falls back to a blank white circle in the status bar / shade.
 *
 * The `notification_icon` drawable and `notification_icon_color` color
 * resource referenced here are generated by the expo-notifications plugin
 * from its `icon` / `color` options in app.json — this plugin must stay in
 * the plugins array AFTER expo-notifications.
 */
const withFirebaseNotificationDefaults = (config) => {
  return withAndroidManifest(config, (config) => {
    // react-native-firebase_messaging's library manifest ships its OWN
    // default_notification_color (@color/white). The manifest merger
    // refuses two different values for the same key, so our color entry
    // must carry tools:replace="android:resource" ("ours wins") — which
    // requires the tools namespace on the manifest root. The icon entry
    // has no library-side counterpart and needs no override.
    const manifest = config.modResults.manifest;
    manifest.$ = manifest.$ ?? {};
    if (!manifest.$['xmlns:tools']) {
      manifest.$['xmlns:tools'] = 'http://schemas.android.com/tools';
    }

    const app = AndroidConfig.Manifest.getMainApplicationOrThrow(config.modResults);

    AndroidConfig.Manifest.addMetaDataItemToMainApplication(
      app,
      'com.google.firebase.messaging.default_notification_icon',
      '@drawable/notification_icon',
      'resource',
    );

    // Added manually (not via addMetaDataItemToMainApplication) because the
    // helper has no way to attach the tools:replace attribute.
    app['meta-data'] = app['meta-data'] ?? [];
    const colorAttrs = {
      'android:name': 'com.google.firebase.messaging.default_notification_color',
      'android:resource': '@color/notification_icon_color',
      'tools:replace': 'android:resource',
    };
    const existing = app['meta-data'].find(
      (item) => item.$?.['android:name'] === colorAttrs['android:name'],
    );
    if (existing) {
      existing.$ = colorAttrs;
    } else {
      app['meta-data'].push({ $: colorAttrs });
    }

    return config;
  });
};

module.exports = withFirebaseNotificationDefaults;
