namespace SportsData.Core.Common
{
    public enum DocumentType
    {
        Athlete = 0,
        AthleteBySeason = 1,
        AthleteImage = 2,
        AthletePosition = 3,
        Award = 4,
        Coach = 5,
        CoachSeason = 6,
        Contest = 7,
        Event = 8,
        EventCompetition = 9,
        EventCompetitionDrive = 10,
        EventCompetitionOdds = 11,
        EventCompetitionProbability = 12,
        EventCompetitionStatus = 13,
        Franchise = 14,
        FranchiseLogo = 15,
        GameSummary = 16,
        GolfCalendar = 17,
        Group = 18,
        GroupBySeason = 19,
        GroupBySeasonLogo = 20,
        GroupLogo = 21,
        Position = 22,
        Scoreboard = 23,
        Season = 24,
        SeasonType = 25,
        Seasons = 26,
        Standings = 27,
        TeamBySeasonLogo = 28,
        TeamInformation = 29,
        TeamRank = 30,
        TeamSeason = 31,
        TeamSeasonAward = 32,
        TeamSeasonCoach = 33,
        TeamSeasonInjuries = 34,
        TeamSeasonLeaders = 35,
        TeamSeasonProjection = 36,
        TeamSeasonRecord = 37,
        TeamSeasonRecordAts = 38,
        TeamSeasonStatistics = 39,
        Venue = 40,
        VenueImage = 41,
        Weeks = 42
    }
}
