namespace SportsData.Core.Common
{
    public enum DocumentType
    {
        Athlete = 0,
        AthleteBySeason = 1,
        AthleteImage = 2,
        AthletePosition = 3,
        Award = 4,
        Coach = 5,
        CoachSeason = 6,
        Contest = 7,
        Event = 8,
        EventCompetition = 9,
        EventCompetitionDrive = 10,
        EventCompetitionOdds = 11,
        EventCompetitionProbability = 12,
        EventCompetitionStatus = 13,
        Franchise = 14,
        FranchiseLogo = 15,
        GameSummary = 16,
        GolfCalendar = 17,
        Group = 18,
        GroupBySeason = 19,
        GroupBySeasonLogo = 20,
        GroupLogo = 21,
        Position = 22,
        Scoreboard = 23,
        Season = 24,
        SeasonFuture = 25,
        SeasonType = 26,
        Seasons = 27,
        Standings = 28,
        TeamBySeasonLogo = 29,
        TeamInformation = 30,
        TeamRank = 31,
        TeamSeason = 32,
        TeamSeasonAward = 33,
        TeamSeasonCoach = 34,
        TeamSeasonInjuries = 35,
        TeamSeasonLeaders = 36,
        TeamSeasonProjection = 37,
        TeamSeasonRecord = 38,
        TeamSeasonRecordAts = 39,
        TeamSeasonStatistics = 40,
        Venue = 41,
        VenueImage = 42,
        Weeks = 43
    }
}
