namespace SportsData.Core.Common
{
    public enum DocumentType
    {
        Athlete,
        AthleteBySeason,
        Award,
        CoachBySeason,
        Contest,
        Franchise,
        GameSummary,
        GroupBySeason,
        Scoreboard,
        Season,
        Seasons,
        Team,
        TeamBySeason,
        TeamInformation,
        Venue,
        Weeks,
        GroupLogo,
        FranchiseLogo,
        GroupBySeasonLogo,
        TeamBySeasonLogo,
        VenueImage,
        Position,
        AthleteImage,
        SeasonType,
        GolfCalendar
    }
}
