using System;

namespace SportsData.Producer.Application.FranchiseSeasons.Queries.GetFranchiseSeasonCompetitionResults;

public record GetFranchiseSeasonCompetitionResultsQuery(Guid FranchiseSeasonId);
