name: Deploy React App to Azure Static Web App

on:
  push:
    branches:
      - main
    paths:
      - 'src/UI/sd-ui/**'  # Only trigger when frontend code changes

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/UI/sd-ui

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18' # Or '20' if your project prefers

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test
      env:
        CI: true

    - name: Build React app
      run: npm run build

    - name: Deploy to Azure Static Web App
      uses: Azure/static-web-apps-deploy@v1
      with:
        azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
        repo_token: ${{ secrets.GITHUB_TOKEN }} # Automatically provided by GitHub
        action: "upload"
        app_location: "src/UI/sd-ui"         # Relative to working directory (src/UI/sd-ui)
        output_location: "build"  # React build output folder
